<?php
/**
 * Created by PhpStorm.
 * User: Vitaly
 * Date: 25.04.2019
 * Time: 19:05
 */

namespace app\widgets;


use function var_export;
use yii\base\Widget;
use yii\helpers\Html;

class TableMVP extends Widget
{
    public $table;//итоговая таблица которую необходимо вывести.

    public $thead; //хедер таблицы

    public $tbody; //Тело таблицы

    public $tfooter; // футер таблицы

    public $isTfooter = false; // включать ли футер таблицы

    public $tableName; //НАименование таблицы

    public $tableNameColumns; // количество столбцов которое занимает название таблицы.

    public $dataProvider;


    public $test;


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(is_callable($this->tableName))
        {
            $this->tableName = call_user_func($this->tableName, $this->dataProvider);
        }

    }

    public function run(){

        return Html::encode($this->tableName);
        return Html::encode($this->table);
    }

}