<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StatisticsService.proto

namespace Cul;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 *Информация о количестве вызовов для множества ключей. key[i] ==> calls[i]
 *
 * Generated from protobuf message <code>cul.ApiKeyCallsCount</code>
 */
class ApiKeyCallsCount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .cul.ApiKey key = 1;</code>
     */
    private $key;
    /**
     * Generated from protobuf field <code>repeated .cul.ApiCallsCount calls = 2;</code>
     */
    private $calls;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cul\ApiKey[]|\Google\Protobuf\Internal\RepeatedField $key
     *     @type \Cul\ApiCallsCount[]|\Google\Protobuf\Internal\RepeatedField $calls
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StatisticsService::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .cul.ApiKey key = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>repeated .cul.ApiKey key = 1;</code>
     * @param \Cul\ApiKey[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKey($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cul\ApiKey::class);
        $this->key = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cul.ApiCallsCount calls = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCalls()
    {
        return $this->calls;
    }

    /**
     * Generated from protobuf field <code>repeated .cul.ApiCallsCount calls = 2;</code>
     * @param \Cul\ApiCallsCount[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCalls($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cul\ApiCallsCount::class);
        $this->calls = $arr;

        return $this;
    }

}

