<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StatisticsService.proto

namespace Cul;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>cul.ApiCallsCount</code>
 */
class ApiCallsCount extends \Google\Protobuf\Internal\Message
{
    /**
     *общее число вызовов
     *
     * Generated from protobuf field <code>.cul.CallsEntry total = 1;</code>
     */
    private $total = null;
    /**
     *количество вызовов по сервисам.
     *
     * Generated from protobuf field <code>map<string, .cul.CallsEntry> for_service = 2;</code>
     */
    private $for_service;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cul\CallsEntry $total
     *          общее число вызовов
     *     @type array|\Google\Protobuf\Internal\MapField $for_service
     *          количество вызовов по сервисам.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StatisticsService::initOnce();
        parent::__construct($data);
    }

    /**
     *общее число вызовов
     *
     * Generated from protobuf field <code>.cul.CallsEntry total = 1;</code>
     * @return \Cul\CallsEntry
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     *общее число вызовов
     *
     * Generated from protobuf field <code>.cul.CallsEntry total = 1;</code>
     * @param \Cul\CallsEntry $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkMessage($var, \Cul\CallsEntry::class);
        $this->total = $var;

        return $this;
    }

    /**
     *количество вызовов по сервисам.
     *
     * Generated from protobuf field <code>map<string, .cul.CallsEntry> for_service = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getForService()
    {
        return $this->for_service;
    }

    /**
     *количество вызовов по сервисам.
     *
     * Generated from protobuf field <code>map<string, .cul.CallsEntry> for_service = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setForService($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cul\CallsEntry::class);
        $this->for_service = $arr;

        return $this;
    }

}

