<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StatisticsService.proto

namespace Cul;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>cul.ApiKeys</code>
 */
class ApiKeys extends \Google\Protobuf\Internal\Message
{
    /**
     *много ключей
     *
     * Generated from protobuf field <code>repeated .cul.ApiKey keys = 1;</code>
     */
    private $keys;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cul\ApiKey[]|\Google\Protobuf\Internal\RepeatedField $keys
     *          много ключей
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StatisticsService::initOnce();
        parent::__construct($data);
    }

    /**
     *много ключей
     *
     * Generated from protobuf field <code>repeated .cul.ApiKey keys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     *много ключей
     *
     * Generated from protobuf field <code>repeated .cul.ApiKey keys = 1;</code>
     * @param \Cul\ApiKey[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cul\ApiKey::class);
        $this->keys = $arr;

        return $this;
    }

}

