<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthService.proto

namespace Cul;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>cul.GenerateTokenResponse</code>
 */
class GenerateTokenResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *Токен
     *
     * Generated from protobuf field <code>bytes token = 1;</code>
     */
    private $token = '';
    /**
     *ROOT CA
     *
     * Generated from protobuf field <code>bytes server_root_ca = 2;</code>
     */
    private $server_root_ca = '';
    /**
     *CLIENT KEY
     *
     * Generated from protobuf field <code>bytes client_key = 3;</code>
     */
    private $client_key = '';
    /**
     *CLIENT CERT
     *
     * Generated from protobuf field <code>bytes client_cert = 4;</code>
     */
    private $client_cert = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *          Токен
     *     @type string $server_root_ca
     *          ROOT CA
     *     @type string $client_key
     *          CLIENT KEY
     *     @type string $client_cert
     *          CLIENT CERT
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AuthService::initOnce();
        parent::__construct($data);
    }

    /**
     *Токен
     *
     * Generated from protobuf field <code>bytes token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *Токен
     *
     * Generated from protobuf field <code>bytes token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->token = $var;

        return $this;
    }

    /**
     *ROOT CA
     *
     * Generated from protobuf field <code>bytes server_root_ca = 2;</code>
     * @return string
     */
    public function getServerRootCa()
    {
        return $this->server_root_ca;
    }

    /**
     *ROOT CA
     *
     * Generated from protobuf field <code>bytes server_root_ca = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServerRootCa($var)
    {
        GPBUtil::checkString($var, False);
        $this->server_root_ca = $var;

        return $this;
    }

    /**
     *CLIENT KEY
     *
     * Generated from protobuf field <code>bytes client_key = 3;</code>
     * @return string
     */
    public function getClientKey()
    {
        return $this->client_key;
    }

    /**
     *CLIENT KEY
     *
     * Generated from protobuf field <code>bytes client_key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setClientKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->client_key = $var;

        return $this;
    }

    /**
     *CLIENT CERT
     *
     * Generated from protobuf field <code>bytes client_cert = 4;</code>
     * @return string
     */
    public function getClientCert()
    {
        return $this->client_cert;
    }

    /**
     *CLIENT CERT
     *
     * Generated from protobuf field <code>bytes client_cert = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setClientCert($var)
    {
        GPBUtil::checkString($var, False);
        $this->client_cert = $var;

        return $this;
    }

}

