<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StatisticsService.proto

namespace Cul;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>cul.ServiceInfo</code>
 */
class ServiceInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *Код сервиса
     *
     * Generated from protobuf field <code>uint64 service_code = 1;</code>
     */
    private $service_code = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $service_code
     *          Код сервиса
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\StatisticsService::initOnce();
        parent::__construct($data);
    }

    /**
     *Код сервиса
     *
     * Generated from protobuf field <code>uint64 service_code = 1;</code>
     * @return int|string
     */
    public function getServiceCode()
    {
        return $this->service_code;
    }

    /**
     *Код сервиса
     *
     * Generated from protobuf field <code>uint64 service_code = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setServiceCode($var)
    {
        GPBUtil::checkUint64($var);
        $this->service_code = $var;

        return $this;
    }

}

