<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthService.proto

namespace Cul;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 *Информация о токене
 *
 * Generated from protobuf message <code>cul.TokenInfo</code>
 */
class TokenInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *id токена
     *
     * Generated from protobuf field <code>uint64 token_id = 1;</code>
     */
    private $token_id = 0;
    /**
     *id ключа связанного с токеном
     *
     * Generated from protobuf field <code>uint64 key_id = 5;</code>
     */
    private $key_id = 0;
    /**
     *текстовое представление ключа
     *
     * Generated from protobuf field <code>string key_data = 6;</code>
     */
    private $key_data = '';
    /**
     *действителен до
     *
     * Generated from protobuf field <code>string expired = 3;</code>
     */
    private $expired = '';
    /**
     *активен или не активен
     *
     * Generated from protobuf field <code>bool active = 4;</code>
     */
    private $active = false;
    /**
     *список доступных сервисов
     *
     * Generated from protobuf field <code>repeated string services = 2;</code>
     */
    private $services;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $token_id
     *          id токена
     *     @type int|string $key_id
     *          id ключа связанного с токеном
     *     @type string $key_data
     *          текстовое представление ключа
     *     @type string $expired
     *          действителен до
     *     @type bool $active
     *          активен или не активен
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $services
     *          список доступных сервисов
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AuthService::initOnce();
        parent::__construct($data);
    }

    /**
     *id токена
     *
     * Generated from protobuf field <code>uint64 token_id = 1;</code>
     * @return int|string
     */
    public function getTokenId()
    {
        return $this->token_id;
    }

    /**
     *id токена
     *
     * Generated from protobuf field <code>uint64 token_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTokenId($var)
    {
        GPBUtil::checkUint64($var);
        $this->token_id = $var;

        return $this;
    }

    /**
     *id ключа связанного с токеном
     *
     * Generated from protobuf field <code>uint64 key_id = 5;</code>
     * @return int|string
     */
    public function getKeyId()
    {
        return $this->key_id;
    }

    /**
     *id ключа связанного с токеном
     *
     * Generated from protobuf field <code>uint64 key_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setKeyId($var)
    {
        GPBUtil::checkUint64($var);
        $this->key_id = $var;

        return $this;
    }

    /**
     *текстовое представление ключа
     *
     * Generated from protobuf field <code>string key_data = 6;</code>
     * @return string
     */
    public function getKeyData()
    {
        return $this->key_data;
    }

    /**
     *текстовое представление ключа
     *
     * Generated from protobuf field <code>string key_data = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyData($var)
    {
        GPBUtil::checkString($var, True);
        $this->key_data = $var;

        return $this;
    }

    /**
     *действителен до
     *
     * Generated from protobuf field <code>string expired = 3;</code>
     * @return string
     */
    public function getExpired()
    {
        return $this->expired;
    }

    /**
     *действителен до
     *
     * Generated from protobuf field <code>string expired = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setExpired($var)
    {
        GPBUtil::checkString($var, True);
        $this->expired = $var;

        return $this;
    }

    /**
     *активен или не активен
     *
     * Generated from protobuf field <code>bool active = 4;</code>
     * @return bool
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     *активен или не активен
     *
     * Generated from protobuf field <code>bool active = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->active = $var;

        return $this;
    }

    /**
     *список доступных сервисов
     *
     * Generated from protobuf field <code>repeated string services = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServices()
    {
        return $this->services;
    }

    /**
     *список доступных сервисов
     *
     * Generated from protobuf field <code>repeated string services = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->services = $arr;

        return $this;
    }

}

