<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthService.proto

namespace Cul;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>cul.Tokens</code>
 */
class Tokens extends \Google\Protobuf\Internal\Message
{
    /**
     *много токенов
     *
     * Generated from protobuf field <code>repeated .cul.TokenInfo tokens = 1;</code>
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Cul\TokenInfo[]|\Google\Protobuf\Internal\RepeatedField $tokens
     *          много токенов
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AuthService::initOnce();
        parent::__construct($data);
    }

    /**
     *много токенов
     *
     * Generated from protobuf field <code>repeated .cul.TokenInfo tokens = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     *много токенов
     *
     * Generated from protobuf field <code>repeated .cul.TokenInfo tokens = 1;</code>
     * @param \Cul\TokenInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cul\TokenInfo::class);
        $this->tokens = $arr;

        return $this;
    }

}

