<?php

namespace app\models;

use const false;
use function var_export;
use Yii;

/**
 * This is the model class for table "add_user_by_email".
 *
 * @property int $id
 * @property string $parent
 * @property string $email
 * @property string $fd
 * @property string $er
 */
class AddUserByEmail extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'add_user_by_email';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['parent', 'email'], 'required'],
            [['email'],'unique'],
            [['email'],'email'],
            [['fd','er'], 'integer'],
            [['parent', 'email','verification_key'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent' => 'Parent',
            'email' => 'Email',
            'fd' => 'Fd',
            'er' => 'Er',
        ];
    }

    public function addOtherParametres() {
        if($this->fd=="on"){
            $this->fd=1;
        }
        if ($this->er=="on"){
            $this->er=1;
        }
        if($this->er==0 and $this->fd==0){
            return false;
        }

        $this->verification_key = Yii::$app->security->generateRandomString();
        return true;
    }

    public function addAgent(){
        $parent = Yii::$app->user->identity;
        $agent = new Register();
        $uniqEmail = User::find()->where(["email"=>$this->email])->exists();
        if(!$uniqEmail) {
            $agent->email = $this->email;
            $agent->username = $this->email;
            $agent->password = Yii::$app->security->generateRandomString(10);
            $agent->purpose = "not information";
            $agent->country = $parent->country;
            $agent->city = $parent->city;
            $agent->user_type = 0; //физ лицо
            $agent->name_organization = $parent->name_organization;
            $agent->confirm_password = $agent->password;
            $agent->REQUESTED_FREE = 0;
            $agent->IS_ACTIVATED = 0;
            $agent->IS_DEFAULT = 0;
            $agent->parent_unit_id = $parent->getId();
            $agent->password_hash = Yii::$app->security->generatePasswordHash($agent->password);
            $agent->access_token = Yii::$app->security->generateRandomString();
            $agent->register_date = time();
//        $agent->reset_password_hash = Yii::$app->security->generateRandomString();
            $agent->update_at = time();

            //использовать save(false);
            if ($agent->save(false)) {

                /*Устанавливаем роли*/
                $ROLE_AGENT = Yii::$app->authManager->getRole("ROLE_AGENT");
                Yii::$app->authManager->assign($ROLE_AGENT, $agent->id);
                return true;
            } else {
//            var_export($agent->errors);die;
                $this->errors["agent"] = "Not create agent";
                return false;
            }
        }else{
            $this->errors["agent"] = "Not create agent";
            return false;
        }






    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $this->sendMessage();
    }

    public function sendMessage() {
        Yii::$app->mailer->compose("add-users",["user"=>$this])
            ->setFrom('test@devlained.ru')
            ->setTo($this->email)
            ->setSubject('You are invited to participate')
            ->send();
    }
}
