<?php

namespace app\models;

use Stripe\Customer;
use Stripe\Stripe;
use Stripe\Token;
use function substr;
use Yii;
use yii\base\Exception;

/**
 * This is the model class for table "stripe".
 *
 * @property int $id
 * @property int $userID
 * @property string $stripeID
 * @property string $cardID
 * @property string $lastNumbers
 */
class myStripe extends \yii\db\ActiveRecord
{
    public $cardNumber;
    public $moth;
    public $year;
    public $cvc;


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'stripe';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['userID', 'stripeID', 'cardID'], 'required'],
            [['userID'], 'integer'],
            [['stripeID', 'cardID'], 'string', 'max' => 255],
            ['lastNumbers', 'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'userID' => 'User ID',
            'stripeID' => 'Stripe ID',
            'cardID' => 'Card ID',
        ];
    }


    /*
     * Подключаем библеотеку stripe
     * */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        require_once(Yii::getAlias("@vendor/").'stripe/stripe-php/init.php');
        Stripe::setApiKey("sk_test_WvgbVGZc4qHh5lF78vUWfB9Z00ZtIRxK38");
    }

    /*
     * Создает карту с данными клиента на стороне Stripe
     * */
    public function createCard($number, $expMoth,$exp_year, $cvc){
        $token = Token::create(
            array("card" => array(
                "number" => "$number",
                "exp_month" => (int)$expMoth,
                "exp_year" => $exp_year,
                "cvc" => $cvc
            ))
        );
        return $token;

    }

    /*
     * Создает клиента на стороне stripe
     * */
    public function createCustomer($cardID){
        return Customer::create([
            "description" => "Customer for jenny.rosen@example.com",
            "source" => $cardID // obtained with Stripe.js
        ]);
    }

    public function createNewConnect() {
        $cardStripe = $this->createCard($this->cardNumber,$this->moth,$this->year,$this->cvc);
        $this->cardID= $cardStripe->id;
        $customer = $this->createCustomer($this->cardID);
        $this->stripeID = $customer->id;
        $this->userID = Yii::$app->user->getId();
        $this->lastNumbers = substr($this->cardNumber,-4); // получаем 4 последние цифры карты.
    }

}
