<?php
/**
 * Created by PhpStorm.
 * User: Vitaly
 * Date: 22.04.2019
 * Time: 3:39
 */

namespace app\models;


use function var_export;
use Yii;
use yii\db\ActiveRecord;

class Users extends ActiveRecord
{
    public static function tableName()
    {
        return "user";
    }

    public $checked;
    public $type;
    public $id;


    public function validateType ($type) {
        if($type== "er" or $type == "fd"){
            return true;
        }else{
            return false;
        }
    }

    public function validateID ($agentID){
        if($this->parent_unit_id == Yii::$app->user->getId()){
            return true;
        }else{
            return false;
        }
    }

    public function loadData($data) {

        if($this->validateID($data['id']) and $this->validateType($data['type'])) {
            $this->checked = $data['checked'];
            $this->type = $data['type'];
            $this->id = $data["id"];
            return true;
        }else{return false;}
    }

    public function setParams() {
        if ($this->type == "fd"){
            if($this->checked == 1){
                $this->FdChecker = 1;
            }else{
                $this->FdChecker = 0;
            }

        }else{
            if($this->checked==1){
                $this->ErChecker = 1;
            }else{
                $this->ErChecker = 0;
            }

        }
    }
    public function beforeSave($insert)
    {
        $this->setParams();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub


    }


}